### ISSUE TITLE
Feature, network Improvements.

### ISSUE THREAD

**Issue by 0xF7A4C6** [adshao/go-binance#466] opened 2023-02-25 16:29 UTC
everything was here ;p

https://github.com/dgrr/fastws
https://github.com/valyala/fasthttp

**Comment by rickstaa** [comment] 2023-05-12 09:12
I agree, fastHTTP support would be wonderful!

**Comment by rickstaa** [comment] 2023-05-12 09:12
Duplicate of https://github.com/adshao/go-binance/issues/307.

**Comment by xyq-c-cpp** [comment] 2024-06-20 10:28
No response for a long time, close this issue

**Closed by xyq-c-cpp** 2024-06-20 10:28 UTC
